### ISSUE TITLE
tulun doesn't work (npm installed globally)

### ISSUE THREAD

**Issue by towerofnix** [liam4/tlnccuwagnf#20]
```
~ $ touch test.tul
~ $ echo "print(\"Hello world\!\");" > test.tul
~ $ tulun test.tul
Error: Cannot find module './grammar'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/tlnccuwagnf/dist/run.js:8:15)
    at Module._compile (module.js:417:34)
    at Object.Module._extensions..js (module.js:426:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

@nanalan could this have to do with local requiring and what not? Also could [this](https://github.com/liam4/tlnccuwagnf/blob/e29d4d7de9e87d60e403c33a0de4b5ebbcce04e9/.npmignore#L5) have anything to do with it?

``` bash
# this is .npmignore
grammar.js
```

**Comment by bates64** [comment]
Yep, that'll be why.

**Comment by bates64** [comment]
Fixed in https://github.com/liam4/tlnccuwagnf/commit/370fd6758df1e5270fe28812d96d7e3e8792a14c
