### ISSUE TITLE
SyntaxError on npm install?

### ISSUE THREAD

**Issue by Arinerron** [liam4/tlnccuwagnf#28]
```
<snip>@<snip> ~ $ sudo npm install -g tlnccuwagnf
[sudo] password for <snip>:  

npm http GET https://registry.npmjs.org/tlnccuwagnf
npm http 304 https://registry.npmjs.org/tlnccuwagnf
npm http GET https://registry.npmjs.org/tlnccuwagnf/-/tlnccuwagnf-0.1.4.tgz
npm http 200 https://registry.npmjs.org/tlnccuwagnf/-/tlnccuwagnf-0.1.4.tgz
npm WARN engine tlnccuwagnf@0.1.4: wanted: {"node":">=4.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm http GET https://registry.npmjs.org/chalk
npm http 200 https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz
npm http 200 https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/supports-color
npm http 200 https://registry.npmjs.org/escape-string-regexp
npm http 200 https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz
npm http 200 https://registry.npmjs.org/has-ansi
npm http 200 https://registry.npmjs.org/supports-color
npm http 200 https://registry.npmjs.org/strip-ansi
npm http 200 https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz
npm http GET https://registry.npmjs.org/ansi-regex
npm http 200 https://registry.npmjs.org/ansi-regex
/usr/local/bin/tulun -> /usr/local/lib/node_modules/tlnccuwagnf/tulun.js

> tlnccuwagnf@0.1.4 postinstall /usr/local/lib/node_modules/tlnccuwagnf
> ./tulun.js --version


/usr/local/lib/node_modules/tlnccuwagnf/tulun.js:5
const args = process.argv.slice(2)
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 8
npm ERR! not ok code 0

```

**Comment by Arinerron** [comment]
Oh, and yes, I did run `sudo npm update -g` first.

**Comment by Arinerron** [comment]
Okay, I solved it. Here's the guide to fix it:
1. Clear NPM's cache:
   `sudo npm cache clean -f`
2. Install a little helper called 'n':
   `sudo npm install -g n`
3. Install latest stable NodeJS version:
   `sudo n stable`
4. Retry the installation of tulun:
   `sudo npm install -g tlnccuwagnf`
